#+title: Le Déluge

#+BEGIN_QUOTE
Après moi, le déluge.

— Louis XV of France
#+END_QUOTE

Le Déluge is a Victoria 3 which follows the events of the French Revolution and the rise of the First French Republic and Empire.

#+BEGIN_QUOTE
But the age of chivalry is gone. That of sophisters, economists, and calculators, has succeeded; and the glory of Europe is extinguished for ever.

— Edmud Burke
#+END_QUOTE

* Philosophy
To what extent should the beginning of the game be railroaded?
Will the player be able to avert the fall of the monarchy?

* Simplification of the situation
Monarchists (Absolute Monarchy)
Orléanist (Constitutional Monarchy)
Girondins (Liberals & Republicans)
Montagnards, [[file:../../../org/roam/20210605150336-enrages.org][Enragés]], [[file:../../../org/roam/20210603205740-sans_culottes.org][Sans-culottes]] (Dirigists & Radicals)

* Coalition Wars
Crises are used to model the Coalition Wars
We need some way to stop France from achieving too much across the span of these wars.
France should be pushed towards the installation of puppet governments.

* Characters

** Leaders
[[file:../../../org/roam/20210605144724-louis_xvi_king_of_france.org][Louis XVI, King of France]]

[[file:../../../org/roam/20210605194430-louis_xvii_king_of_france.org][Louis XVII, King of France]]

** Interest groups

*** Aristocrats

*** Capitalists

*** Clergy
[[file:../../../org/roam/20210605144407-antoine_eleonor_leon_leclerc_de_juigne.org][Antoine-Éléonor-Léon Leclerc de Juigné]]

*** Military
[[file:../../../org/roam/20210605144751-charles_francois_dumouriez.org][Charles François Dumouriez]]

*** Labour unions
[[file:../../../org/roam/20210603205715-jean_paul_marat.org][Jean-Paul Marat]]

[[file:../../../org/roam/20210603222658-maximilien_robespierre.org][Maximilien Robespierre]]

** Generals
[[file:../../../org/roam/20210605144751-charles_francois_dumouriez.org][Charles François Dumouriez]]

[[file:../../../org/roam/20210605200546-francois_christophe_de_kellermann.org][François Christophe de Kellermann]]

** Admirals

* External references
https://eu4.paradoxwikis.com/French_Revolution
