* Napoleon Bonaparte
"Send me 300 francs; that sum will enable me to go to Paris. There, at least, one can cut a figure and surmount obstacles. Everything tells me I shall succeed. Will you prevent me from doing so for the want of 100 crowns?\n— Napoleon Bonaparte"
"From the heights of these pyramids, forty centuries look down on us.\n— Napoleon Bonaparte"
"I ought to have died at Waterloo.\n— Napoleon Bonaparte"
"A form of government that is not the result of a long sequence of shared experiences, efforts, and endeavors can never take root.\n— Napoleon Bonaparte"
From the sublime to the ridiculous is but a step.
The word impossible is not French.
All authority is in the throne; and what is the throne? This wooden frame covered with velvet? No, I am the throne.
Wherever wood can swim, there I am sure to find this flag of England.
What then is, generally speaking, the truth of history? A fable agreed upon.
Women are nothing but machines for producing children.
I am a monarch of God's creation, and you reptiles of the earth dare not oppose me. I render an account of my government to none save God and Jesus Christ.
Immortality is the best recollection one leaves.
I am for the whites, because I am white; I have no other reason, yet that is reason good enough. How was it possible to grant liberty to the Africans, to men without any kind of civilization, who did not even know what a colony meant, or that there was such a place as France?
He who fears being conquered is certain of defeat.
What is the government? Nothing, unless supported by opinion.
The people must not be counted upon; they cry indifferently : 'Long live the King!' and 'Long live the Conspirators!' a proper direction must be given to them, and proper instruments employed to effect it.
Greatness is nothing unless it be lasting.
Destiny urges me to a goal of which I am ignorant. Until that goal is attained I am invulnerable, unassailable. When Destiny has accomplished her purpose in me, a fly may suffice to destroy me.
In politics nothing is immutable. Events carry within them an invincible power. The unwise destroy themselves in resistance. The skillful accept events, take strong hold of them and direct them.
Never interfere with an enemy whilst he's making a mistake.

* Robespierre
The People is always worth more than individuals.
The secret of liberty is to enlighten men, as that of tyranny is to keep them in ignorance.
It is with regret that I pronounce the fatal truth: Louis must die, so that the country may live.
Our revolution has made me feel the full force of the axiom that history is fiction and I am convinced that chance and intrigue have produced more heroes than genius and virtue.
Any institution which does not suppose the people good, and the magistrate corruptible, is evil.
When the government violates the people’s rights, insurrection is, for the people and each portion of the people, the most sacred of rights and the most indispensable of duties.
Men of all countries are brothers, and the different peoples should help one another to the best of their ability, like citizens of the same state.
lf the attribute of popular government in peace is virtue, the attribute of popular government in revolution is at one and the same time virtue and terror, virtue without which terror is fatal, terror without which virtue is impotent. The terror is nothing but justice, prompt, severe, inflexible; it is thus an emanation of virtue.
The government in a revolution is the despotism of liberty against tyranny.

* Marat
Five or six hundred [aristocratic] heads lopped off would have assured you repose and happiness; a false humanity has restrained your arm and suspended your blows; it will cost the lives of millions of your brothers.
People, give thanks to the gods! Your most redoubtable enemy has fallen beneath the scythe of Fate.
No, liberty is not made for us: we are too ignorant, too vain, too presumptuous, too cowardly, too vile, too corrupt, too attached to rest and to pleasure, too much slaves to fortune to ever know the true price of liberty. We boast of being free! To show how much we have become slaves, it is enough just to cast a glance on the capital and examine the morals of its inhabitants.
Fifty years of anarchy await you, and you will emerge from it only by the power of some dictator who will arise — a true statesman and patriot. O prating people, if you did but know how to act!

* Louis Antoine de Saint-Just
When a people, having become free, establish wise laws, their revolution is complete.
One cannot reign innocently: the insanity of doing so is evident. Every king is a rebel and a usurper.
Those who make revolutions by halves do nothing but dig their own tombs.
Most arts have produced miracles, while the art of government has produced nothing but monsters.
A nation regenerates itself only upon heaps of corpses.
The Revolution is frozen; all its principles are weakened; there remains only red caps worn by intriguers. The exercise of terror has made crime blasé, as strong liquors made the palace blasé. 
In every Revolution a dictator is needed to save the state by force, or censors to save it by virtue. 
Dare! — this word contains all the politics of our revolution. 
Happiness is a new idea in Europe. 
Let Revolutionists be Romans, not Tatars. 
I am not of any faction, I will fight them all. 

* Louis XIV
I am going away, but the State will always remain. 
I could sooner reconcile all Europe than two women. 
L'État, c'est moi. 

* Louis XVI

* Marie Antoinette
It is quite certain that in seeing the people who treat us so well despite their own misfortune, we are more obliged than ever to work hard for their happiness.
Courage! I have shown it for years; think you I shall lose it at the moment when my sufferings are to end? 

* Rousseau
A country cannot subsist well without liberty, nor liberty without virtue. 
Virtue is a state of war, and to live in it means one always has some battle to wage against oneself.

* Voltaire
The first priest was just the first rogue to meet the first fool.

* Wellington
I believe I forgot to tell you I was made a Duke. 
The history of a battle, is not unlike the history of a ball. Some individuals may recollect all the little events of which the great result is the battle won or lost, but no individual can recollect the order in which, or the exact moment at which, they occurred, which makes all the difference as to their value or importance.
It has been a damned nice thing — the nearest run thing you ever saw in your life. On Waterloo.
All the business of war, and indeed all the business of life, is to endeavour to find out what you don't know by what you do; that's what I called "guessing what was at the other side of the hill."
Well, Bonaparte has not given me any idea of his projects, and as my plans will depend on his, how can you expect to tell me what mine are?
Believe me, nothing except a battle lost can be half so melancholy as a battle won: the bravery of my troops hitherto saved me from the greater evil; but to win such a battle as this of Waterloo, at the expens of so many gallant friends, could only be termed a heavy misfortune but for the result to the public.
Give me night or give me Blücher 
The national character of the three kingdoms was strongly marked in my army. I found the English regiments always in the best humour when we were well supplied with beef; the Irish when we were in the wine countries, and the Scotch when the dollars for pay came up.
For the mob, use grapeshot.
The foreign policy of England should be to maintain peace, not only for herself but between the powers of the world. This should be her policy, not only because she can have no interest in a change of the state of possession of the several powers...but because she has the most extensive commercial relations depending upon peace with each and all the powers of the world, the interruption of which must be injurious to her prosperity. 
You must build your House of Parliament on the river: so... that the populace cannot exact their demands by sitting down round you. 
We always have been, we are, and I hope that we always shall be, detested in France. 
I have seen their backs before, madam. 
I used to say of him (Napoleon) that his presence on the field made the difference of forty thousand men.
The French system of conscription brings together a fair sample of all classes; ours is composed of the scum of the earth — the mere scum of the earth. It is only wonderful that we should be able to make so much out of them afterwards.

* Others
"Après moi, le déluge.\n— Louis XV of France"
"But the age of chivalry is gone. That of sophisters, economists, and calculators, has succeeded; and the glory of Europe is extinguished for ever.\n— Edmund Burke"
"Peoples do not judge in the same way as courts of law; they do not hand down sentences, they throw thunderbolts; they do not condemn kings, they drop them back into the void; and this justice is worth just as much as that of the courts.\n— Robespierre"
"It was the best of times, it was the worst of times, . . . it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us.\n— Charles Dickens"
You will follow us soon! Your house will be beaten down and salt sown in the place where it stood! — Georges Danton to Robespierre on his way to the guillotine
By the end of the game, Roussillon will be French.
It is too soon to tell — Zhou Enlai, on the consequences of the French Revolution

